architect/inventory

- .github/workflows/build.yml
- package.json
> Windowsing

- changelog.md
- package.json
- src/config/pragmas/http.js
- test/integration/preferences-test.js
- test/unit/src/config/pragmas/http-test.js
> Move ASAP into Inventory

- changelog.md
- package.json
- src/config/pragmas/http.js
- src/config/pragmas/index.js
- src/config/pragmas/src-dirs.js
- src/config/pragmas/static.js
- src/defaults/index.js
- src/lib/asap-src.js
- test/unit/src/config/pragmas/http-test.js
- test/unit/src/config/pragmas/src-dirs-test.js
- test/unit/src/config/pragmas/static-test.js
- test/unit/src/defaults/index-test.js
> Adds lambdasBySrcDir for source dir Lambda lookups

- src/config/pragmas/index.js
- src/config/pragmas/ws.js
> Tidy up pragma visitor routine

- changelog.md
- package.json
- src/config/pragmas/static.js
- src/config/project/prefs.js
- test/integration/preferences-test.js
- test/mock/max/preferences.arc
- test/unit/src/config/pragmas/static-test.js
> Add @sandbox-startup to preferences

- package.json
- src/config/pragmas/populate-lambda/_plugins.js
- test/unit/src/config/pragmas/plugins-test.js
relates to architect/architect#1115, will include this in the upcoming plugins RC
> allow for plugin authors to implement either pluginFunctions or functions plugin interface method

- changelog.md
- src/config/pragmas/index.js
- src/config/pragmas/shared.js
- src/config/pragmas/views.js
> Fix shared + views error propagation

- changelog.md
- package.json
- src/defaults/index.js
- test/unit/src/defaults/index-test.js
> Include registry of all + Lambda pragmas in _arc metadata

- .github/workflows/build.yml
- changelog.md
- package.json
> Remove support for Node.js 10.x

- changelog.md
- package.json
- src/config/_upsert.js
- src/config/pragmas/app.js
- src/config/pragmas/http.js
- src/config/pragmas/populate-lambda/_events.js
- src/config/pragmas/populate-lambda/_http.js
- src/config/pragmas/populate-lambda/_scheduled.js
- src/config/pragmas/populate-lambda/_streams.js
- src/config/pragmas/populate-lambda/_websockets.js
- src/config/pragmas/populate-lambda/index.js
- src/config/pragmas/src-dirs.js
- src/config/pragmas/static.js
- src/config/pragmas/streams.js
- src/config/pragmas/validate/_lib.js
- src/config/project/prefs.js
- src/get.js
- src/read/reader.js
- src/validate/arn.js
- test/unit/src/config/_upsert-test.js
- test/unit/src/config/pragmas/http-test.js
> Fix multiple `@aws` `policies` + `layers` on the same line

- changelog.md
- package.json
- src/index.js
- test/integration/preferences-test.js
- test/unit/src/config/project/preferences-test.js
> Integrate Architect Parser v5

- changelog.md
- package.json
- src/defaults/function-config.js
- test/integration/function-config-test.js
- test/mock/function-config/src/http/get-config/config.arc
- test/unit/src/config/_upsert-test.js
- test/unit/src/defaults/function-config-test.js
> Lambda architecture

- changelog.md
- package.json
- src/config/pragmas/populate-lambda/get-runtime.js
- src/validate/config.js
- test/unit/src/validate/config-test.js
- test/unit/src/validate/index-test.js
> Harden runtime validation by ensuring non-string values will fail gracefully

- changelog.md
- package.json
- src/config/pragmas/http.js
- src/config/pragmas/populate-lambda/index.js
- src/config/pragmas/sort/http.js
- src/config/pragmas/validate/_http.js
- src/config/project/index.js
- src/config/project/prefs.js
- src/env/index.js
- src/lib/http-methods.js
- test/unit/src/config/pragmas/http-test.js
> Add HTTP route sorting; fixes #977

- changelog.md
- src/defaults/function-config.js
- src/validate/config.js
- test/integration/function-config-test.js
- test/mock/function-config/global-alias/src/http/get-config/config.arc
- test/mock/function-config/no-global/src/http/get-config/config.arc
- test/unit/src/config/_upsert-test.js
- test/unit/src/defaults/function-config-test.js
- test/unit/src/validate/config-test.js
> Add support for configuring Lambda's ephemeral storage feature

- changelog.md
- package.json
- src/config/pragmas/plugins.js
- src/config/pragmas/populate-lambda/index.js
- src/config/pragmas/populate-other/index.js
- src/config/pragmas/proxy.js
- src/config/pragmas/shared.js
- src/config/pragmas/static.js
- src/config/pragmas/tables-indexes.js
- src/config/pragmas/tables.js
- src/config/pragmas/validate/_lib.js
- src/config/pragmas/validate/_shared.js
- src/config/pragmas/validate/_static.js
- src/config/pragmas/validate/_tables.js
- src/config/pragmas/validate/index.js
- src/config/pragmas/views.js
- src/lib/index.js
- src/lib/is.js
- test/lib/index.js
- test/unit/src/config/pragmas/plugins-test.js
- test/unit/src/config/pragmas/populate-lambda/index-test.js
- test/unit/src/config/pragmas/populate-other/index-test.js
- test/unit/src/config/pragmas/proxy-test.js
- test/unit/src/config/pragmas/shared-test.js
- test/unit/src/config/pragmas/static-test.js
- test/unit/src/config/pragmas/tables-indexes-test.js
- test/unit/src/config/pragmas/tables-test.js
- test/unit/src/config/pragmas/views-test.js
> Add support for new setter plugin APIs, minor bug fixes

- changelog.md
- src/config/pragmas/http.js
- test/unit/src/config/pragmas/http-test.js
Thanks @oliverturner!
Thanks again!
> Fix `@static spa true` setting issue

- changelog.md
- src/config/pragmas/static.js
- test/unit/src/config/pragmas/static-test.js
> Merge `ignore` settings from `set.static` plugins and project manifest

- .eslintignore
- changelog.md
- package.json
- src/config/pragmas/plugins.js
- test/integration/inventory-params-test.js
- test/mock/plugins-lambda/app.arc
- test/mock/plugins-lambda/src/plugins/custom-pubsub-cjs.js
- test/mock/plugins-lambda/src/plugins/custom-pubsub-esm.mjs
- test/mock/plugins-lambda/src/plugins/rando.js
> Add support for plugins authored as ES modules

- changelog.md
- src/config/pragmas/tables-indexes.js
- test/unit/src/config/pragmas/tables-indexes-test.js
I still suck at git
Thanks again!
> Fix wonky merge of @filmaj's projection attributes

- changelog.md
- package.json
- src/config/pragmas/plugins.js
- src/config/pragmas/populate-lambda/get-handler.js
- src/config/project/plugins/runtimes.js
- test/mock/plugin-validation/invalid/src/plugins/a-plugin-1.js
- test/mock/plugin-validation/valid/src/plugins/a-plugin-1.js
- test/mock/plugin-validation/valid/src/plugins/a-plugin-2.js
- test/unit/src/config/pragmas/plugins-test.js
- test/unit/src/config/pragmas/populate-lambda/get-handler-test.js
- test/unit/src/config/project/plugins/runtimes-test.js
> Flesh out `compiled` runtime plugin support

- src/config/project/plugins/runtimes.js
- test/unit/src/config/project/plugins/runtimes-test.js
> Compiled default baseRuntime

- changelog.md
- src/config/pragmas/sort/http.js
- test/unit/src/config/pragmas/http-test.js
> Refactor HTTP route sorter

- changelog.md
- src/validate/paths.js
- test/unit/src/validate/paths-test.js
> Improve path validation for multi-tenant Lambdae

- changelog.md
- src/config/pragmas/tables.js
- test/unit/src/config/pragmas/tables-test.js
> Allow lowcase `ttl` @tables property type

- changelog.md
- src/config/pragmas/populate-lambda/get-handler.js
- test/unit/src/config/pragmas/populate-lambda/get-handler-test.js
> Add support for additional Python Lambda handler filenames

- changelog.md
- src/config/pragmas/populate-lambda/index.js
- test/unit/src/config/pragmas/populate-lambda/index-test.js
> Fix AWS Lambda handler configuration for Python, Ruby, and custom handlers

- changelog.md
- src/config/_upsert.js
- test/unit/src/config/_upsert-test.js
> Add ability for unknown function-level configuration settings to be arrays / vectors
